In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"Desktop\Data.csv")
df.head(7)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No

In [3]:
from sklearn.impute import SimpleImputer 

In [4]:
imputer = SimpleImputer(missing_values = np.nan, strategy ='mean')

In [5]:
imputer.fit(df.iloc[:,1:3])
df.iloc[:,1:3]=imputer.transform(df.iloc[:,1:3])

In [6]:
df.head(7)

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No

In [7]:
X = df.iloc[:,0:3]
X.head()

Country   Age        Salary
0   France  44.0  72000.000000
1    Spain  27.0  48000.000000
2  Germany  30.0  54000.000000
3    Spain  38.0  61000.000000
4  Germany  40.0  63777.777778

In [8]:
Y = df.iloc[:,-1]
Y.head()

0     No
1    Yes
2     No
3     No
4    Yes
Name: Purchased, dtype: object

# Encoding Categorical Values

Here one hot encoding can be done as if we label countries as 1,2,3 it will miss interpret the outcome.. Thus we will create 3 groups.

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder',OneHotEncoder(),[0])] ,remainder = 'passthrough' )
X = np.array(ct.fit_transform(X))

In [10]:
X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

# Lable encoder

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [12]:
y = le.fit_transform(Y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


# Feature Scaling 
( apply after splitting in train and test set)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 1)  #80% for train and 20% for test

In [14]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(8, 5)
(8,)
(2, 5)
(2,)


### *_Standardization_* : -3<X<3 and *_Normalization_* : 0<X<1

#####  >_Std = x-mean/sd_<    > _Normal = x-min/max-min_<
1)Standardisation works well all the time.
2)Normalisation is recommended in the cases when u have maximum  features of normal type.

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [16]:
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
print(X_train)

[[ 0.          0.          1.         -0.19159184 -1.07812594]
 [ 0.          1.          0.         -0.01411729 -0.07013168]
 [ 1.          0.          0.          0.56670851  0.63356243]
 [ 0.          0.          1.         -0.30453019 -0.30786617]
 [ 0.          0.          1.         -1.90180114 -1.42046362]
 [ 1.          0.          0.          1.14753431  1.23265336]
 [ 0.          1.          0.          1.43794721  1.57499104]
 [ 1.          0.          0.         -0.74014954 -0.56461943]]


In [17]:
X_test[:,3:] = sc.transform(X_test[:,3:])
print(X_test)

[[ 0.          1.          0.         -1.46618179 -0.9069571 ]
 [ 1.          0.          0.         -0.44973664  0.20564034]]


## -x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-

# Regression( Simple linear regression)

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
df = pd.read_csv(r"Desktop\Salary_Data.csv")

In [20]:
X = df.iloc[:,:-1]
X.head()

YearsExperience
0              1.1
1              1.3
2              1.5
3              2.0
4              2.2

In [21]:
y = df.iloc[:,-1]
y.head()

0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
Name: Salary, dtype: float64

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 1)  #80% for train and 20% for test

In [23]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(24, 1)
(24,)
(6, 1)
(6,)


In [24]:
y_train.head()

26    116969.0
3      43525.0
24    109431.0
22    101302.0
23    113812.0
Name: Salary, dtype: float64

In [25]:
regressor = LinearRegression()

In [26]:
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)